configs:
    ts-serve:
        content: |
            {"TCP":{"443":{"HTTPS":true}},
            "Web":{"$${TS_CERT_DOMAIN}:443":
                {"Handlers":{"/":
                {"Proxy":"http://127.0.0.1:3000"}}}},
            "AllowFunnel":{"$${TS_CERT_DOMAIN}:443":false}}

services:
    tailscale:
        image: tailscale/tailscale:latest
        container_name: ts-${SERVICE}
        hostname: ${SERVICE}
        environment:
            - TS_AUTHKEY=${TS_AUTHKEY}
            - TS_SERVE_CONFIG=/config/serve.json
            - TS_STATE_DIR=/var/lib/tailscale
            - TS_ENABLE_HEALTH_CHECK=true # Enable healthcheck endpoint: "/healthz"
            - TS_LOCAL_ADDR_PORT=127.0.0.1:41234 # The <addr>:<port> for the healthz endpoint
            - TS_USERSPACE=false
            - TS_AUTH_ONCE=true
        configs:
            - source: ts-serve
              target: /config/serve.json
        volumes:
            - ${DATA_DIR}/${SERVICE}/ts/config:/config
            - ${DATA_DIR}/${SERVICE}/ts/state:/var/lib/tailscale
        devices:
            - /dev/net/tun:/dev/net/tun # Network configuration for Tailscale to work
        cap_add:
            - NET_ADMIN
            - NET_RAW
        #ports:
        #  - 0.0.0.0:${SERVICEPORT}:${SERVICEPORT} # Binding port ${SERVICE}PORT to the local network - may be removed if only exposure to your Tailnet is required
        # If any DNS issues arise, use your preferred DNS provider by uncommenting the config below
        # dns:
        #   - ${DNS_SERVER}
        healthcheck:
            test: [
                    "CMD",
                    "wget",
                    "--spider",
                    "-q",
                    "http://127.0.0.1:41234/healthz",
                ] # Check Tailscale has a Tailnet IP and is operational
            interval: 1m # How often to perform the check
            timeout: 10s # Time to wait for the check to succeed
            retries: 3 # Number of retries before marking as unhealthy
            start_period: 10s # Time to wait before starting health checks
        restart: unless-stopped

    forgejo:
        image: codeberg.org/forgejo/forgejo:15
        container_name: app-${SERVICE}
        network_mode: service:tailscale
        depends_on:
            tailscale:
                condition: service_healthy
        environment:
            - USER_UID=1000
            - USER_GID=1000
            # https://forgejo.org/docs/latest/admin/config-cheat-sheet/
            - FORGEJO__server__ROOT_URL=https://${FORGEJO_HOSTNAME}
            - FORGEJO__server__SSH_DOMAIN=${FORGEJO_HOSTNAME}
            - TZ=${TZ}
        volumes:
            - ${DATA_DIR}/${SERVICE}/data:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        # ports:
        #   - '3000:3000'
        #   - '222:22'
        restart: unless-stopped
