services:
    golink:
        image: ghcr.io/tailscale/golink:main
        container_name: golink
        restart: unless-stopped
        user: root
        environment:
            - TS_AUTHKEY=${TS_AUTHKEY}
        volumes:
            - ${DATA_DIR}/golink/data:/home/nonroot
